FROM node:16-alpine as prod

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build 

FROM nginx:alpine

WORKDIR /usr/share/nginx/html

COPY --from=prod /app/dist .

COPY  default.conf /etc/nginx/conf.d

EXPOSE 5173
# run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]